#!/usr/bin/env python
#-*- coding=utf-8 -*-
##############################
import time,re
import requests
class read_html(object):
	def read(self,domain):
		content = str(requests.get(domain).content)
		full_content = content.split('\n')
		return full_content
class format_pict(object):
	def format_pict(self):
		return re.compile(r'.*(http.+?\.jpg|http.+?\.png|http.+?\.gif)')

class zhuaqu(object):
	def __init__(self):
		self.pict_list = list()
	def picture_list(self,domain):
		full_content = read_html().read(domain)
		format_pipei = format_pict().format_pict()
		for line in full_content:
			if format_pipei.search(line):
				xxx = "".join(format_pipei.findall(line))
				self.pict_list.append(xxx)
			else:
				pass
		return self.pict_list
class dowland(object):
	def main(self,domain):
		for line in zhuaqu().picture_list(domain):
			f = file(line.split('/')[-1],'wb')
			pict_content = requests.get(line,verify=False).content
			f.write(pict_content)
			f.close() 
a = dowland()
print a.main('http://douban.com/')
