#!/usr/bin/env python
# -*- coding=utf-8 -*-
##############################
import time
import re
import os
import requests

requests.packages.urllib3.disable_warnings()
class zhuaqu(object):
    def __init__(self):
        """

        :rtype: zhuaqu domain pictur_url and dowland
        """
        self.pict_list = list()
        self.format_pipei = re.compile(r'.*(http.+?\.jpg|http.+?\.png|http.+?\.gif).*')

    def __str__(self):
        return 'Object %s' % (self.pict_list)

    __repr__ = __str__

    def __picture_list(self, domain):
        self.pict_list = list()
        content = str(requests.get(domain).content)
        full_content = content.split('\n')
        for line in full_content:
            if self.format_pipei.search(line):
                xxx = "".join(self.format_pipei.findall(line))
                self.pict_list.append(xxx)
        return self.pict_list

    def main(self, domain):
        dir_name = domain.split('/')[2]
        os.mkdir(dir_name)
        os.chdir(dir_name)
        for line in self.__picture_list(domain):
            f = file(line.split('/')[-1], 'wb')
            pict_content = requests.get(line, verify=False).content
            f.write(pict_content)
            f.close()
        os.chdir(os.pardir)
        return True



a = zhuaqu()
a.main('http://douban.com/')
a.main('http://www.dianping.com/')
a.main('http://www.qq.com/')
